services:
  web:
    build: .
    ports:
      - "80:5000"
    depends_on:
      - db
    environment:
      - SECRET_KEY=supersecretkey
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/flask_db
    volumes:
      - .:/app
    networks:
      - db_net

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flask_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - db_net

volumes:
  pgdata:

networks:
  db_net:
    driver: bridge